version: "3.7"
services:
  importer:
    build: ./importer/
    image: docker.pkg.github.com/avoinglam/h4og-dashboard/importer
    volumes:
     - ./config/:/usr/src/app/config/
     - ./data/:/usr/src/app/data/
  backend:
    build: ./backend/
    image: docker.pkg.github.com/avoinglam/h4og-dashboard/backend
    volumes:
      - ./config/:/usr/src/app/config/
      - ./data/:/usr/src/app/data/
    ports:
      - 8080:80